{{- if .Values.postgres.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data
  labels:
    {{- include "banksphere.labels" . | nindent 4 }}
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: {{ .Values.postgres.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.postgres.storage }}
{{- end }}
